#! /bin/bash

### Filter out flags for tfer that start with --
args=()
flags=()
for arg in "$@"; do
  if [[ $arg == --* ]]; then
    flags+=("$arg")
  else
    args+=("$arg")
  fi
done
set -- "${args[@]}" "${flags[@]}"

for flag in "${flags[@]}"; do
  ### --help
  if [[ $flag == --help ]]; then
    echo "Usage: tfer [options] [terraform command and flags]"
    echo "Example: tfer --dir=terraform/ plan"
    echo ""
    echo "Options:"
    echo "  --help          Show this help message"
    echo "  --dir=<path>    Change to directory <path> before executing"
    echo "  --link-only     Only create symlinks, do not run terraform"
    exit 0
  fi
  ### Change directory if --dir flag is set
  if [[ $flag == --dir=* ]]; then
    dir="${flag#--dir=}"
    cd "$dir"
  fi
done

### Create .tfer directory
mkdir -p .tfer

### Create symlinks
for file in $(find $PWD -name "*.tf" -o -name "*.tfvars" | grep -v .tfer); do
  relative_path="${file#$PWD/}"
  target=".tfer/${relative_path//\//_}"
  if [[ ! -L "$target" || "$(readlink "$target")" != "$file" ]]; then
    ln -sf "$file" "$target"
  fi
done
### Remove missing links
find .tfer -type l | while read -r link; do
  if [[ ! -e "$link" ]]; then
    rm "$link"
  fi
done

ln -sf ${PWD}/.terraform.lock.hcl .tfer/.terraform.lock.hcl
ln -sf ${PWD}/.terraform .tfer/.terraform
cd .tfer

### Run terraform
if [[ ! " ${flags[@]} " =~ " --link-only " ]]; then
  terraform "${args[@]}"
fi
